apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - port: 5001
      name: user-main
      targetPort: 5001
    - port: 8089
      name: user-performance
      targetPort: 8089
  type: LoadBalancer