apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-main
          image: diliplakshya/user-main
          ports:
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /
              port: 5001
            periodSeconds: 10
            initialDelaySeconds: 5
          imagePullPolicy: Always
          env:
            - name: FOLDER
              valueFrom:
                configMapKeyRef:
                  name: user-data-store-env
                  key: folder
            - name: INFO_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-data-store-env
                  key: info_host
          volumeMounts:
            - mountPath: /app/data
              name: app-volume
        - name: user-performance
          image: diliplakshya/user-performance
          ports:
            - containerPort: 8089
          imagePullPolicy: Always
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: host-pvc